CREATE SCHEMA core;

CREATE TABLE core.ref_land (
    LAND_ID INTEGER NOT NULL,
    LAND VARCHAR(200) NOT NULL,
    ERSTELLT_AM TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    QUELLE VARCHAR(20) NOT NULL,
    CONSTRAINT PK_LAND PRIMARY KEY(LAND_ID)
);

CREATE TABLE core.ref_ort (
    ORT_ID INTEGER NOT NULL,
    ORT VARCHAR(200) NOT NULL,
    LAND_ID INTEGER NOT NULL,
    ERSTELLT_AM TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    QUELLE VARCHAR(20) NOT NULL,
    CONSTRAINT PK_ORT PRIMARY KEY(ORT_ID),
    CONSTRAINT FK_R_LAND FOREIGN KEY(LAND_ID) REFERENCES core.ref_land(LAND_ID)
);

CREATE TABLE core.hub_hersteller (
    HERSTELLER_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LOAD_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    RECORD_SOURCE TEXT NOT NULL,
    HERSTELLER_CODE CHAR(3) NOT NULL
);

CREATE TABLE core.sat_hersteller ( 
    HERSTELLER_ID INT NOT NULL,
    LOAD_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    RECORD_SOURCE TEXT NOT NULL,
    HERSTELLER_NAME VARCHAR(200) NOT NULL,
    ERSTELLT_AM TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    QUELLE VARCHAR(20) NOT NULL,
    CONSTRAINT PK_HERSTELLER PRIMARY KEY(HERSTELLER_ID, LOAD_DATE),
    CONSTRAINT FK_HERSTELLER_ID FOREIGN KEY(HERSTELLER_ID) REFERENCES core.hub_hersteller(HERSTELLER_ID)
);

CREATE TABLE core.hub_fahrzeug (
    FAHRZEUG_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LOAD_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    RECORD_SOURCE TEXT NOT NULL,
    FIN CHAR(17) UNIQUE NOT NULL
);

CREATE TABLE core.sat_fahrzeug (
    FAHRZEUG_ID INT NOT NULL,
    LOAD_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    RECORD_SOURCE TEXT NOT NULL,
    MODELL VARCHAR(200) NOT NULL,
    PRODUKTIONSDATUM DATE,
    ERSTELLT_AM TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    QUELLE VARCHAR(50) NOT NULL,
    CONSTRAINT PK_FAHRZEUG PRIMARY KEY(FAHRZEUG_ID, LOAD_DATE),
    CONSTRAINT FK_FAHRZEUG_ID FOREIGN KEY(FAHRZEUG_ID) REFERENCES core.hub_fahrzeug(FAHRZEUG_ID)
);

CREATE TABLE core.hub_kunde (
    KUNDE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LOAD_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    RECORD_SOURCE TEXT NOT NULL,
    KUNDE_ACCOUNT VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE core.sat_kunde (
    KUNDE_ID INT NOT NULL,
    LOAD_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    RECORD_SOURCE TEXT NOT NULL,
    VORNAME VARCHAR(200) NOT NULL,
    NACHNAME VARCHAR(200) NOT NULL,
    GESCHLECHT VARCHAR(20) NOT NULL, 
    GEBURTSDATUM DATE,
    WOHNORT_ID INTEGER NOT NULL,
    ERSTELLT_AM TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    QUELLE VARCHAR(50) NOT NULL,
    CONSTRAINT PK_KUNDE PRIMARY KEY(KUNDE_ID, LOAD_DATE),
    CONSTRAINT FK_KUNDE_ORT FOREIGN KEY(WOHNORT_ID) REFERENCES core.ref_ort(ORT_ID),
    CONSTRAINT FK_KUNDE_ID FOREIGN KEY(KUNDE_ID) REFERENCES core.hub_kunde(KUNDE_ID)
);

CREATE TABLE core.link_fzg_kauf (
    FZG_KAUF_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LOAD_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    RECORD_SOURCE TEXT NOT NULL,
    KUNDE_ID INT NOT NULL,
    FAHRZEUG_ID INT NOT NULL,
    CONSTRAINT FK_FAHRZEUG_ID FOREIGN KEY(FAHRZEUG_ID) REFERENCES core.hub_fahrzeug(FAHRZEUG_ID),
    CONSTRAINT FK_KUNDE_ID FOREIGN KEY(KUNDE_ID) REFERENCES core.hub_kunde(KUNDE_ID)
);

CREATE TABLE core.sat_fzg_kauf (
    FZG_KAUF_ID INT NOT NULL,
    LOAD_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    RECORD_SOURCE TEXT NOT NULL,
    KFZ_KENNZEICHEN VARCHAR(20) NOT NULL,
    KAUFDATUM DATE,
    LIEFERDATUM DATE,
    KAUFPREIS INTEGER,
    RABATT_PCT INTEGER,
    ERSTELLT_AM TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    QUELLE VARCHAR(50) NOT NULL,
    CONSTRAINT PK_FZG_KAUF PRIMARY KEY(FZG_KAUF_ID, LOAD_DATE),
    CONSTRAINT FK_FZG_KAUF_ID FOREIGN KEY(FZG_KAUF_ID) REFERENCES core.link_fzg_kauf(FZG_KAUF_ID)
);

CREATE TABLE core.sat_messung (
    FAHRZEUG_ID INT NOT NULL,
    LOAD_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    RECORD_SOURCE TEXT NOT NULL,
    ZEIT_UNTRANSFORMIERT INT NOT NULL,
    GESCHWINDIGKEIT INT NOT NULL,
    EMPFANGEN TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MESSUNG PRIMARY KEY (FAHRZEUG_ID, LOAD_DATE),
    CONSTRAINT FK_FAHRZEUG_ID FOREIGN KEY(FAHRZEUG_ID) REFERENCES core.hub_fahrzeug(FAHRZEUG_ID)
);
